In [ ]:
#simple array creation
import numpy as np
a= np.array([0,1,2,3])
print(a)
#checking the type
type(a)
#numeric type of elements
a.dtype #checking the datatype of the elements of the array


[0 1 2 3]


dtype('int64')

In [ ]:
import numpy as np
a= np.array([0,1,2,3])
print(a)
type(a)  #checking the type of the array as a whole


[0 1 2 3]


numpy.ndarray

In [ ]:
#bytes per elements
import numpy as np
a= np.array([0,1,2,3])
print(a)
print(a.itemsize)


[0 1 2 3]
8


In [ ]:
#bytes of memory used
print(a.nbytes)

32


In [ ]:
#array shape
a.shape

(4,)

In [ ]:
#No. of dimensions
a.ndim

1

In [ ]:
# Multidimensional array
a= np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#shape of the array
a.shape

(2, 4)

In [ ]:
#No. of elements
a.size

8

In [ ]:
#Get or set the elements
a[1,2]=-1
print(a)

[[ 1  2  3  4]
 [ 5  6 -1  8]]


In [ ]:
#address 2nd row using single index
print(a[1])  #printing all elements of 2nd row

[ 5  6 -1  8]


In [ ]:
#to find out which versin
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np._version_)


[[1 2 3 4]
 [5 6 7 8]]


AttributeError: module 'numpy' has no attribute '_version_'

In [ ]:
#Zero dimension array
import numpy as np
arr=np.array(2) #if square brackets are not used, it shows zero dimensional array
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
n=arr.ndim # give the dimension of array
print("No. of dimensions:",n)

2
1
()
<class 'numpy.ndarray'>
No. of dimensions: 0


In [ ]:
# One dimensional array
import numpy as np
arr=np.array([2])
print("The array is :",arr)
print("Size of the array is",arr.size)
print("Shape of the array",arr.shape)
print("type of array",type(arr))
n=arr.ndim
print("No. of dimensions:",n)

The array is : [2]
Size of the array is 1
Shape of the array (1,)
type of array <class 'numpy.ndarray'>
No. of dimensions: 1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("The array is :",arr)
print("Size of the array is",arr.size)
print("Shape of the array",arr.shape)
print("type of array",type(arr))
n=arr.ndim
print("No. of dimensions:",n)

The array is : [1 2 3 4 5]
Size of the array is 5
Shape of the array (5,)
type of array <class 'numpy.ndarray'>
No. of dimensions: 1


In [ ]:
#2-D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("The array is:",arr)
print("Size of the array:",arr.size)
print("Shape of the array",arr.shape)
print("Type of array:",type(arr))
n=arr.ndim
print("No. of dimensions:",n)


The array is: [[1 2 3]
 [4 5 6]]
Size of the array: 6
Shape of the array (2, 3)
Type of array: <class 'numpy.ndarray'>
No. of dimensions: 2


In [ ]:
# if single element of array belongs to float datatype, then all integers also get changed to float
import numpy as np
arr=np.array([[2.0,1],[1,2]])
print(arr)

[[2. 1.]
 [1. 2.]]


In [ ]:
import numpy as np
arr=np.array([[2.0,1],[1]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#To create an array with 5-D and verify the same
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("No. of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
No. of dimensions: 5


In [ ]:
#Accessing the 1st element of array
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])  # to find which element is there at 0 index

1


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,0])
print(arr[1,0])
print(arr[1,2])

print(arr(1,2))

1
4
6


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5]])
print(arr[0,0])
print(arr[1,0])
print(arr[1,2])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#To calculate the sum of 3rd and 4th elements from the array
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr[2]+arr[3])

[1 2 3 4]
7


In [ ]:
# Creating a 2D aray of size 2*5 and accessing the 2nd element on 1st dimension
import numpy as np
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print("2nd element on 1st dimension:",arr[0,1])
print("2nd element on 2nd dimension:",arr[1,1])

2nd element on 1st dimension: 2
2nd element on 2nd dimension: 6


In [ ]:
#Accessing the 3 rd element of the 2nd array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
print()
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

6


In [ ]:
#Accessing the 2nd element of the 2nd array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
print()
print(arr[0,1,1])
print(arr[0,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

5
[4 5 6]


In [ ]:
#Basic arithmatic operations using 1D array
import numpy as np
arr=np.array([1,2,3,4,5])
print("Sum =",arr[0]+arr[2])
print("Difference=",arr[3]-arr[2])
print("Product=",arr[1]*arr[3])
print("Division=",arr[4]/arr[1])

Sum = 4
Difference= 1
Product= 8
Division= 2.5


In [ ]:
# slicing 1D array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:6])
print(arr[:5])
