In [1]:
#crop yeild for 4 farmers over 5years(in tones)
import numpy as np
crop_yield =np.array([
    [12.5,13.2,14.1,13.8,15.2],# farm1
    [10.3,11.5,10.8,12.1,11.9],#farm2
    [15.1,14.8,16.2,15.5,16.8],#farm3
    [11.2,10.9,12.3,11.7,12.8] #farm4
    ])
print("crop yiels array(tons):",crop_yield)
print(f'\nshape:{crop_yield.shape}')
print(f'\ndata type:{crop_yield.dtype}')
print(f'\ntotal elements:{crop_yield.size}')
print(f'\nnum of dimensions:{crop_yield.ndim}')


crop yiels array(tons): [[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)

data type:float64

total elements:20

num of dimensions:2


In [3]:
#agricultural analysis poeration
import numpy as np
total_yield_per_farm=np.sum(crop_yield)
avg_yield_per_farm=np.mean(crop_yield,axis=1)

avgl_yield_per_season=np.mean(crop_yield,axis=0)
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)
print(f'\ntotal yield per farm:{total_yield_per_farm} tons')
print(f'\naverage yield per farm:{avg_yield_per_farm} tons')
print(f'\naverage yield per season:{avgl_yield_per_season}tons')
print(f'\nmax yield:{max_yield} tons')
print(f'\nmin yield:{min_yield}tons')




total yield per farm:262.7 tons

average yield per farm:[13.76 11.32 15.68 11.78] tons

average yield per season:[12.275 12.6   13.35  13.275 14.175]tons

max yield:16.8 tons

min yield:10.3tons


In [ ]:
# find best performing farm
best_farm=np.argmax(avg_yield_per_farm) #np.argmax() does not return max value itself-it returns where that value is located

print("\nbest perforing farm: farm", best_farm+1)
print("their avg yeild:",round(avg_yield_per_farm[best_farm],2),"tons")


best perforing farm: farm 3
their avg yeild: 15.68 tons


In [4]:
#boolean indexing:find exceptional yield
exceptional=crop_yield >16
print(exceptional)

print('\n exceptional yield(>16):')
print(crop_yield[exceptional])

[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False False False False False]]

 exceptional yield(>16):
[16.2 16.8]


In [5]:
#conditional operations:classify yields
categories=np.where