In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=pd.read_csv('/content/Product_purchase (1).csv')

In [ ]:
dataset

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [ ]:
print(dataset.columns[[2,3]])

Index(['Age', 'EstimatedSalary'], dtype='object')


In [ ]:
print(dataset.columns[4])

Purchased


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="entropy",max_depth=None,
                             min_samples_split=5,min_samples_leaf=2)

model.fit(x_train,y_train)
print(model)

y_pred_dec=model.predict(x_test)
y_pred_dec

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)

from sklearn.metrics import accuracy_score
print("Decision Tree",accuracy_score(y_test,y_pred_dec))

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[64  4]
 [ 4 28]]
Decision Tree 0.92


In [ ]:
from sklearn.linear_model import LogisticRegression
modelr=LogisticRegression(random_state=0)

modelr.fit(x_train,y_train)
print(modelr)

y_pred_lr=model.predict(x_test)
y_pred_lr

from sklearn.metrics import confusion_matrix
cmlr=confusion_matrix(y_test,y_pred_lr)
print(cmlr)

from sklearn.metrics import accuracy_score
print("Logisic Regression",accuracy_score(y_test,y_pred_lr))

LogisticRegression(random_state=0)
[[64  4]
 [ 4 28]]
Logisic Regression 0.92


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
RFmodel.fit(x_train,y_train)

y_pred_rf=RFmodel.predict(x_test)


from sklearn.metrics import confusion_matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)

from sklearn.metrics import accuracy_score
print("Random Forest",accuracy_score(y_test,y_pred_rf))

[[63  5]
 [ 3 29]]
Random Forest 0.92
